{{- if and (.Values.mockServer.enabled) (.Values.mockServer.ingress.enabled) -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $servicePort := .Values.mockServer.service.port -}}
{{- $ingressPath := .Values.mockServer.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "chart.name" . }}-mock-server
    chart: {{ template "chart.name_version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.mockServer.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.mockServer.ingress.tls }}
  tls:
  {{- range .Values.mockServer.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.mockServer.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: serviceport
  {{- end }}
{{- end }}
